### ISSUE TITLE
lib.a缺失

### ISSUE THREAD

**Issue by jeremydev97** [plctlab/riscv-ci#16]
Error: cannot find default versions of the ISA extension `k'
Assembler messages:
Error: cannot find default versions of the ISA extension `k'
/tmp/ccpWbMwm.s:3: Error: cannot find default versions of the ISA extension `k'
/tmp/ccdEmlzC.s:3: Error: cannot find default versions of the ISA extension `k'
make[6]: *** [Makefile:415: lib_a-memmove_chk.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[6]: *** [Makefile:421: lib_a-mempcpy_chk.o] Error 1
Assembler messages:
Error: cannot find default versions of the ISA extension `k'
/tmp/ccUNvDjb.s:3: Error: cannot find default versions of the ISA extension `k'
make[6]: *** [Makefile:397: lib_a-chk_fail.o] Error 1
Assembler messages:
Error: cannot find default versions of the ISA extension `k'
Assembler messages:
Error: cannot find default versions of the ISA extension `k'
/tmp/ccGpHn7a.s:3: Error: cannot find default versions of the ISA extension `k'
/tmp/ccuBbJwF.s:3: Error: cannot find default versions of the ISA extension `k'
make[6]: *** [Makefile:409: lib_a-memcpy_chk.o] Error 1
make[6]: *** [Makefile:403: lib_a-stack_protector.o] Error 1
Assembler messages:
Error: cannot find default versions of the ISA extension `k'
/tmp/ccXx3yIb.s:3: Error: cannot find default versions of the ISA extension `k'
make[6]: *** [Makefile:427: lib_a-memset_chk.o] Error 1
make[6]: Leaving directory '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/build-newlib/riscv32-unknown-elf/newlib/libc/ssp'
Making all in .
make[6]: Entering directory '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/build-newlib/riscv32-unknown-elf/newlib/libc'
rm -f libc.a
rm -rf tmp
mkdir tmp
cd tmp; \
 for i in argz/lib.a stdlib/lib.a ctype/lib.a search/lib.a stdio/lib.a   string/lib.a signal/lib.a time/lib.a locale/lib.a reent/lib.a  errno/lib.a misc/lib.a ssp/lib.a   syscalls/lib.a  machine/lib.a ; do \
   riscv32-unknown-elf-ar x ../$i; \
 done; \
riscv32-unknown-elf-ar rc ../libc.a *.o
riscv32-unknown-elf-ar: ../argz/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../stdlib/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../ctype/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../search/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../stdio/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../string/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../signal/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../time/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../locale/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../reent/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../errno/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../misc/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../ssp/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../syscalls/lib.a: No such file or directory
riscv32-unknown-elf-ar: ../machine/lib.a: No such file or directory
riscv32-unknown-elf-ar: *.o: No such file or directory
make[6]: *** [Makefile:1034: libc.a] Error 1

**Comment by pz9115** [comment]
You should not use k as a arch args, the toolchain only recongnize the subextension string as default. Try to use 
`--with-arch=rv64gc_zbkb_zbkc_zbkx_zknd_zkne_zknh_zkr_zksed_zksh_zkt --with-abi=lp64d --with-multilib-generator="rv64gc_zbkb_zbkc_zbkx_zknd_zkne_zknh_zkr_zksed_zksh_zkt-lp64d--"` as the configure options to compile the RISC-V GNU toolchain.

**Comment by jeremydev97** [comment]
Thanks, it works well
