### ISSUE TITLE
configure : WORNING : unrecongnized options: --with-multilib-generator

### ISSUE THREAD

**Issue by Jeremy-Jia** [plctlab/riscv-ci#24]
when I execute the "./configure ...." command, it shows "configure : WORNING : unrecongnized options: --with-multilib-generator",      and it it cant generate it multilib.

**Comment by lazyparser** [comment]
Hi @Jeremy-Jia 

There are dozens scripts in the repo. Would you like to share your build env and the repo/sript you are building/using?

**Comment by lazyparser** [comment]
Seems that the issue is irrelevant with riscv-ci. close it.
