### ISSUE TITLE
aes32dsi 指令的optioncode和spec里编码不一致

### ISSUE THREAD

**Issue by Jeremy-Jia** [plctlab/riscv-ci#32]

**Comment by Jeremy-Jia** [comment]
查了spec发现这条汇编指令的opcode和spec规定的不一致
![image](https://user-images.githubusercontent.com/36725890/140680343-112452df-ebb7-45fb-8305-1b3b9982ff0a.png)

**Comment by Jeremy-Jia** [comment]
1

**Comment by pz9115** [comment]
> 查了spec发现这条汇编指令的opcode和spec规定的不一致 ![image](https://user-images.githubusercontent.com/36725890/140680343-112452df-ebb7-45fb-8305-1b3b9982ff0a.png)

你好，请问一下这条指令的opcode是在哪里看到的呢 @Jer

**Comment by Jeremy-Jia** [comment]
使用make newlib编译出gcc, 然后在c里面调用aes32的builtin函数，使用objdump反汇编得到的图片上的码，转换成二进制后发现和crypto spec上的不一致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午3:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32)




  
查了spec发现这条汇编指令的opcode和spec规定的不一致 
  
你好，请问一下这条指令的opcode是在哪里看到的呢 @jer

**Comment by pz9115** [comment]
> 使用make newlib编译出gcc, 然后在c里面调用aes32的builtin函数，使用objdump反汇编得到的图片上的码，转换成二进制后发现和crypto spec上的不一致
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月8日(周一) 下午3:12 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 查了spec发现这条汇编指令的opcode和spec规定的不一致 你好，请问一下这条指令的opcode是在哪里看到的呢 @jer — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


你好，我在本地实验时没有发现这个问题，

![image](https://user-images.githubusercontent.com/43362020/140705376-65b6c4ff-d976-450f-a684-d8db81eaaca9.png)


我们最新的更新是在：

https://github.com/pz9115/riscv-gcc/tree/k-ext-rebase
https://github.com/pz9115/riscv-binutils-gdb/tree/k-ext-rebase

**Comment by Jeremy-Jia** [comment]
以aes32dsi为例，opcode是对的，但是func7段的25~29位对不上，不知是什么问题导致的？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plctlab/riscv-ci"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32)





  
使用make newlib编译出gcc, 然后在c里面调用aes32的builtin函数，使用objdump反汇编得到的图片上的码，转换成二进制后发现和crypto spec上的不一致
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年11月8日(周一) 下午3:12 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 查了spec发现这条汇编指令的opcode和spec规定的不一致 你好，请问一下这条指令的opcode是在哪里看到的呢 @jer — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好，我在本地实验时没有发现这个问题，
 

 
我们最新的更新是在：
 
https://github.com/pz9115/riscv-gcc/tree/k-ext-rebase
 https://github.com/pz9115/riscv-binutils-gdb/tree/k-ext-rebase

**Comment by Jeremy-Jia** [comment]
以aes32dsi为例，opcode是对的，但是func7段的第25~29对不上来，不知是是什么原因？
从 Windows 版邮件发送

发件人: Jiawei
发送时间: 2021年11月8日 16:06
收件人: plctlab/riscv-ci
抄送: Jeremy; Author
主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32)

使用make newlib编译出gcc, 然后在c里面调用aes32的builtin函数，使用objdump反汇编得到的图片上的码，转换成二进制后发现和crypto spec上的不一致
…
---原始邮件--- 发件人: @.> 发送时间: 2021年11月8日(周一) 下午3:12 收件人: @.>; 抄送: @.@.>; 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 查了spec发现这条汇编指令的opcode和spec规定的不一致 你好，请问一下这条指令的opcode是在哪里看到的呢 @jer — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
你好，我在本地实验时没有发现这个问题，

我们最新的更新是在：
https://github.com/pz9115/riscv-gcc/tree/k-ext-rebase
https://github.com/pz9115/riscv-binutils-gdb/tree/k-ext-rebase

**Comment by pz9115** [comment]
> 以aes32dsi为例，opcode是对的，但是func7段的第25~29对不上来，不知是是什么原因？ 从 Windows 版邮件发送 发件人: Jiawei 发送时间: 2021年11月8日 16:06 收件人: plctlab/riscv-ci 抄送: Jeremy; Author 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 使用make newlib编译出gcc, 然后在c里面调用aes32的builtin函数，使用objdump反汇编得到的图片上的码，转换成二进制后发现和crypto spec上的不一致 … ---原始邮件--- 发件人: @.> 发送时间: 2021年11月8日(周一) 下午3:12 收件人: @.>; 抄送: @.@.>; 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 查了spec发现这条汇编指令的opcode和spec规定的不一致 你好，请问一下这条指令的opcode是在哪里看到的呢 @jer — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，我在本地实验时没有发现这个问题， 我们最新的更新是在： https://github.com/pz9115/riscv-gcc/tree/k-ext-rebase https://github.com/pz9115/riscv-binutils-gdb/tree/k-ext-rebase — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

func7段是和bs段与rs2段在一起的，bs段反汇编后是10，rs2段反汇编后是01100，结合aesdsi的func7是10101得到[31:20]为：101010101100=>aac, 请参考最新的spec手册1.0.0-rc5：https://github.com/riscv/riscv-crypto/releases/tag/v1.0.0-rc5-scalar

![image](https://user-images.githubusercontent.com/43362020/140712612-8d31a2ce-415f-4840-b34a-b1fbf86186e4.png)

**Comment by Jeremy-Jia** [comment]
Thanks, it helps a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plctlab/riscv-ci"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32)





  
以aes32dsi为例，opcode是对的，但是func7段的第25~29对不上来，不知是是什么原因？ 从 Windows 版邮件发送 发件人: Jiawei 发送时间: 2021年11月8日 16:06 收件人: plctlab/riscv-ci 抄送: Jeremy; Author 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 使用make newlib编译出gcc, 然后在c里面调用aes32的builtin函数，使用objdump反汇编得到的图片上的码，转换成二进制后发现和crypto spec上的不一致 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年11月8日(周一) 下午3:12 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [plctlab/riscv-ci] aes32dsi 指令的optioncode和spec里编码不一致 (Issue #32) 查了spec发现这条汇编指令的opcode和spec规定的不一致 你好，请问一下这条指令的opcode是在哪里看到的呢 @jer — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，我在本地实验时没有发现这个问题， 我们最新的更新是在： https://github.com/pz9115/riscv-gcc/tree/k-ext-rebase https://github.com/pz9115/riscv-binutils-gdb/tree/k-ext-rebase — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
func7段是和bs段与rs2段在一起的，bs段反汇编后是10，rs2段反汇编后是01100，结合aesdsi的func7是10101得到[31:20]为：101010101100=&gt;aac, 请参考最新的spec手册1.0.0-rc5：https://github.com/riscv/riscv-crypto/releases/tag/v1.0.0-rc5-scalar
