### ISSUE TITLE
GNU-CI调整

### ISSUE THREAD

**Issue by pz9115** [plctlab/riscv-ci#39]
根据目前开发进度变化，需要追踪的CI有所减少，下面是不再需要的CI的URL：

https://ci.rvperf.org/view/GNU/job/fsf-gnu-toolchain-master-all-ubuntu1804/

https://ci.rvperf.org/view/GNU/job/fsf-gnu-toolchain-master-all-ubuntu2004/

https://ci.rvperf.org/view/GNU/job/gnu-toolchan-rvv-1.0/

https://ci.rvperf.org/view/GNU/job/linsinan-riscv-gnu-toolchain-ubuntu1804/

https://ci.rvperf.org/view/GNU/job/linsinan-riscv-gnu-toolchain-ubuntu2004/

https://ci.rvperf.org/view/GNU/job/plct-gnu-b-extension-1804/

https://ci.rvperf.org/view/GNU/job/plct-gnu-b-extension-2004/

https://ci.rvperf.org/view/GNU/job/plct-gnu-k-extension-2004-script/

https://ci.rvperf.org/view/GNU/job/plct-gnu-k-extension-ubuntu1804/

https://ci.rvperf.org/view/GNU/job/plct-gnu-k-extension-ubuntu2004/

https://ci.rvperf.org/view/GNU/job/plct-gnu-zfinx-rv32E/

https://ci.rvperf.org/view/GNU/job/plct-gnu-zfinx-rv32gc/

https://ci.rvperf.org/view/GNU/job/plct-gnu-zfinx-rv64gc/

https://ci.rvperf.org/view/GNU/job/riscv-gnu-toolchain-master-ubuntu1804/

https://ci.rvperf.org/view/GNU/job/riscv-gnu-toolchain-master-ubuntu2004/

https://ci.rvperf.org/view/GNU/job/riscv-gnu-toolchain-rvv-ubuntu1804/

**Comment by lazyparser** [comment]
除了 linsinan-* 的2个jobs，其它都已经disable。相关的脚本可以考虑发个PR删除。
