### ISSUE TITLE
pts04 clone qemu 的时候会失败

### ISSUE THREAD

**Issue by lazyparser** [plctlab/riscv-ci#7]
```
+ git submodule update --init
Cloning into '/home/jenkins_node/workspace/ml-fsf-gcc-master-ubuntu2004/riscv-gnu-toolchain/qemu'...
fatal: unable to access 'https://git.qemu.org/git/qemu.git/': server certificate verification failed. CAfile: none CRLfile: none
fatal: clone of 'https://git.qemu.org/git/qemu.git' into submodule path '/home/jenkins_node/workspace/ml-fsf-gcc-master-ubuntu2004/riscv-gnu-toolchain/qemu' failed
Failed to clone 'qemu'. Retry scheduled
Cloning into '/home/jenkins_node/workspace/ml-fsf-gcc-master-ubuntu2004/riscv-gnu-toolchain/qemu'...
fatal: unable to access 'https://git.qemu.org/git/qemu.git/': server certificate verification failed. CAfile: none CRLfile: none
fatal: clone of 'https://git.qemu.org/git/qemu.git' into submodule path '/home/jenkins_node/workspace/ml-fsf-gcc-master-ubuntu2004/riscv-gnu-toolchain/qemu' failed
Failed to clone 'qemu' a second time, aborting
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by lazyparser** [comment]
我注意到

在 ubuntu 2004 上下载 QEMU 仓库会遇到

fatal: unable to access 'https://git.qemu.org/git/qemu.git/': server certificate verification failed. CAfile: none CRLfile: none

而下载github的repo却OK的。

在 ubuntu 1804 上就不会出现这个error

Google 之，是一个已知的 CA 问题。但是SO上的方法试验之后还是不行。各位有遇到过么

**Comment by jeremydev97** [comment]
21.04 clone qemu出错：
jeremy@jeremy-ubuntu:~/Desktop/k-ext-work/riscv-gnu-toolchain$ git submodule update --init
Cloning into '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/riscv-binutils'...
Cloning into '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/riscv-dejagnu'...


Cloning into '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/riscv-gcc'...


Cloning into '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/riscv-gdb'...
Cloning into '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/riscv-glibc'...
Cloning into '/home/jeremy/Desktop/k-ext-work/riscv-gnu-toolchain/riscv-newlib'...
fatal: Needed a single revision
Unable to find current revision in submodule path 'qemu'

**Comment by lazyparser** [comment]
fixed by update CA
